### ISSUE TITLE
unraid  6.11.5错误

### ISSUE THREAD

**Issue by WindsOfWorld** [ich777/intel-gpu-top#2]
version：6.11.5

kernel:：Linux Tower 5.19.17-Unraid #2 SMP PREEMPT_DYNAMIC Wed Nov 2 11:54:15 PDT 2022 x86_64 13th Gen Intel(R) Core(TM) i5-13400 GenuineIntel GNU/Linux

CPU：13th Gen Intel® Core™ i5-13400 @ 4059 MHz

dmesg log :

segfault at 78 ip 0000000000405f32 sp 00007ffe95b1a790 error 4 in intel_gpu_top[403000+a000] 

Code: 9d e0 ef ff ff 48 8b 9d 68 e7 ff ff 48 89 9d e8 ef ff ff 4c 89 f3 eb 12 48 89 d8 48 83 c0 08 48 89 c3 48 8b 00 48 85 c0 74 11 <80> 78 38 00 74 e8 48 8b 78 30 e8 0f d1 ff ff eb dd 31 db 49 8d 84
run error：

Failed to detect engines! (No such file or directory)
(Kernel 4.16 or newer is required for i915 PMU support.)
Segmentation fault

**Comment by ich777** [comment]
@WindsOfWorld thank you for the report, please post your Diagnostics.

Are you sire that the card is not bound to VFIO?

**Comment by WindsOfWorld** [comment]
this is my Diagnostics [tower-diagnostics-20230420-1104.zip](https://github.com/ich777/intel-gpu-top/files/11280389/tower-diagnostics-20230420-1104.zip)

**Comment by ich777** [comment]
> this is my Diagnostics [tower-diagnostics-20230420-1104.zip](https://github.com/ich777/intel-gpu-top/files/11280389/tower-diagnostics-20230420-1104.zip)

I think this is caused by SRIOV.

Try to run this: `intel_gpu_top drm:/dev/dri/card0` or `intel_gpu_top drm:/dev/dri/renderD128`

If this also fails try to uninstall SRIOV and see if it fixes the issue.

**Comment by WindsOfWorld** [comment]
Thanks a lot for your help
 I uninstalled SR-IOV and it worked

**Comment by ich777** [comment]
Yes, SRIOV is as far as I know only a third party implementation and is not guaranteed to work AFAIK.

Can this be closed now?

**Comment by WindsOfWorld** [comment]
Yes, Please
